#forked from https://github.com/GoogleCloudPlatform/getting-started-java

runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

# [START env_variables]
env_variables:
  BUCKET_NAME: whitley-best-buy-autocomplete-bucket
# [END env_variables]

manual_scaling:
  instances: 1